name: syntax checker
on: pull_request

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
    - name: checkout git repo
      uses: actions/checkout@v3
    - name: run check
      uses: hadolint/hadolint-action@v3.0.0
      with:
        recursive: true
        verbose: true
  